
services:
  gold-price:  
    # image: ktpm-cs3-gold-price:latest
    container_name: gold-price
    build: 
      context: .
      dockerfile: ./goldprice/Dockerfile
    ports:
      - 3008:3008
  foreign-currency:  
    # image: ktpm-cs3-foreign-currency:latest
    container_name: foreign-currency
    build: 
      context: .
      dockerfile: ./foreigncurrency/Dockerfile
    ports:
      - 3009:3009
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    ports:
    - 8080:8080
    privileged: true
    devices:
      - /dev/kmsg:dev/kmsg
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - gold-price
      - foreign-currency
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
    - gold-price
    - foreign-currency
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 4000:3000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - .docker/monitoring/data:/var/lib/grafana
    restart: always
    depends_on:
    - prometheus
