scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: gold-price 
  scrape_interval: 5s
  static_configs:
  - targets: 
    - gold-price:3008 #Our express app container
- job_name: foreign-currency
  scrape_interval: 5s
  static_configs:
  - targets: 
    - foreign-currency:3009 #Our express app container


